# Marxan rottnest4

require(shiny)

shinyUI(pageWithSidebar(

    #headerPanel(paste0("Run MarZone - Rottnest Island ",sUserID)),
    headerPanel("Run MarZone - Rottnest Island"),
    
    sidebarPanel(
        actionButton("mrun","Run"), 
        br(),
        br(),
        textOutput("buttonfeedback"),
        #br(),
        conditionalPanel(condition = "input.tabs == 'Map'",
            br(),
            radioButtons("map", "Map to display:",
                         list("Best solution" = "bestmap",
                              "Solution M" = "runMmap",
                              "Selection frequency zone N" = "ssolnNmap"))
        ),
        conditionalPanel(condition = "input.tabs == 'Map' & (input.map == 'bestmap' | input.map == 'runMmap' | input.map == 'ilpmap')",
                         HTML("<img src='http://marxan.net/images/white.png' /></a>"),
                         HTML(ZoneNames[1]),
                         br(),
                         HTML("<img src='http://marxan.net/images/green.png' /></a>"),
                         HTML(ZoneNames[2]),
                         br(),
                         HTML("<img src='http://marxan.net/images/blue10.png' /></a>"),
                         HTML(ZoneNames[3])
                        ),
        conditionalPanel(condition = "input.tabs == 'Map' & input.map == 'ssolnNmap'",
                         HTML("Selection frequency"),
                         br(),
                         HTML("<img src='http://marxan.net/images/blue10.png' /></a>"),
                         HTML("91-100"),
                         br(),
                         HTML("<img src='http://marxan.net/images/blue9.png' /></a>"),
                         HTML("81-90"),
                         br(),
                         HTML("<img src='http://marxan.net/images/blue8.png' /></a>"),
                         HTML("71-80"),
                         br(),
                         HTML("<img src='http://marxan.net/images/blue7.png' /></a>"),
                         HTML("61-70"),
                         br(),
                         HTML("<img src='http://marxan.net/images/blue6.png' /></a>"),
                         HTML("51-60"),
                         br(),
                         HTML("<img src='http://marxan.net/images/blue5.png' /></a>"),
                         HTML("41-50"),
                         br(),
                         HTML("<img src='http://marxan.net/images/blue4.png' /></a>"),
                         HTML("31-40"),
                         br(),
                         HTML("<img src='http://marxan.net/images/blue3.png' /></a>"),
                         HTML("21-30"),
                         br(),
                         HTML("<img src='http://marxan.net/images/blue2.png' /></a>"),
                         HTML("11-20"),
                         br(),
                         HTML("<img src='http://marxan.net/images/blue1.png' /></a>"),
                         HTML("1-10"),
                         br(),
                         HTML("<img src='http://marxan.net/images/white.png' /></a>"),
                         HTML("0")
                        ),
        conditionalPanel(condition = "input.tabs == 'Cluster'",
                         br(),
                         HTML("<img src='http://marxan.net/images/black.png' /></a>"),
                         HTML(ZoneNames[1]),
                         br(),
                         HTML("<img src='http://marxan.net/images/green.png' /></a>"),
                         HTML(ZoneNames[2]),
                         br(),
                         HTML("<img src='http://marxan.net/images/blue10.png' /></a>"),
                         HTML(ZoneNames[3])
                        ),
        conditionalPanel(condition = "input.tabs == 'Map'",
            checkboxInput('shoreline_fishing', HTML("<img src='http://marxan.net/images/yellow.png' /></a> Shoreline Fishing"), FALSE),
            checkboxInput('fisheries_notice_301', HTML("<img src='http://marxan.net/images/red.png' /></a> Fisheries Notice 301"), FALSE),
            checkboxInput('fisheries_notice_332', HTML("<img src='http://marxan.net/images/red.png' /></a> Fisheries Notice 332"), FALSE),
            checkboxInput('recfish_game', HTML("<img src='http://marxan.net/images/orange.png' /></a> Recfish Game"), FALSE),
            checkboxInput('recfish_trolling', HTML("<img src='http://marxan.net/images/purple.png' /></a> Recfish Trolling"), FALSE)
        ),
        conditionalPanel(condition = "input.tabs == 'Table'",
            br(),
            radioButtons("tabletype", "Table type:",
                         list("Inputs" = "input",
                              "Outputs" = "output"))
        ),
        conditionalPanel(condition = "input.tabs == 'Table' & input.tabletype == 'input'",
            radioButtons("table_i", "Table to display:",
                         list("Features" = "spec",
                              "Zones" = "zones",
                              "Zone boundary cost" = "zoneboundcost",
                              "Zone contribution" = "zonecontrib",
                              "Zone cost" = "zonecost",
                              "Costs" = "costs"))
        ),
        conditionalPanel(condition = "input.tabs == 'Table' & input.tabletype == 'output'",
            radioButtons("table_o", "Table to display:",
                         list("Summary" = "sumtable",
                              "Best solution Missing values" = "mvbesttable",
                              "Solution M Missing values" = "mvNtable"))
        ),
        conditionalPanel(condition = "input.tabs == 'Table' & input.tabletype == 'input' & input.table_i == 'zoneboundcost'",
            selectInput("whichzbc","Boundary weight to edit",
                        choices = c("zones 1<->2","zones 1<->3","zones 2<->3")),
            numericInput("zbc", "Boundary weight:",0,min=0),
            actionButton("savezbc","Save boundary weight")
        ),
        conditionalPanel(condition = "input.tabs == 'Table' & input.tabletype == 'input' & input.table_i == 'spec'",
            selectInput("feature", "Choose a species to edit:",
                        choices = c("All features","SEAGRASS","SEAGRASS1","SEAGRASS2","FISH1","FISH2","FISH3","INVERT","SHALLOW","MEDIUM","DEEP","ABAS","APUF","BEACH","PUD","PARDUNES","RSF","CORAL1","CORAL2","CORAL3","INTERLEDGE","ISLNDISLET","SEAGR_REEF","MOLLUSCS1","MOLLUSCS2","REEF","REEFAWASH","SAND","ECHINODERM")),
            numericInput("prop", "Target:",0.3,min=0,max=1,step=0.1),
            numericInput("spf", "SPF:",1000,min=0),
            br(),
            actionButton("savetargetspf","Save Target and SPF")
        ),
        conditionalPanel(condition = "input.tabs == 'Map' & input.map == 'ssolnNmap'",
            br(),
            textOutput("zonename"),
            br(),
            sliderInput("n", "Zone N:", 
                        value = 3,
                        min = 1, 
                        max = 3, step = 1)
        ),
        conditionalPanel(condition = "(input.tabs == 'Map' & input.map == 'runMmap') | (input.tabs == 'Table' & input.tabletype == 'output' & input.table_o == 'mvNtable')",
            br(),
            sliderInput("m", "Solution M:", 
                        value = 1,
                        min = 1, 
                        max = iNUMREPS, step = 1)
        ),
        conditionalPanel(condition = "input.prop == -1",
                         numericInput("refreshinput", "Test Input", 0))
    ),

    mainPanel(
        tabsetPanel(id="tabs",
                tabPanel("Map", plotOutput('marxanmap')),
                tabPanel("Table", tableOutput('marxantable')),
                tabPanel("Cluster", plotOutput("plot2ds"),
                                    plotOutput("plotdendogram"))
        )
    )
))

